apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fastendpoints
spec:
  selector:
    matchLabels:
      app: hello-fastendpoints
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-fastendpoints
    spec:
      containers:
      - name: hello-fastendpoints
        image: mattiascodes/hello-fast-endpoints:1.0
        ports:
        - containerPort: 8080
